#!/bin/bash
#SBATCH -J orcunThesis # job name
#SBATCH -o run_1.out # output and error file name
#SBATCH --nodes=1 # total number of nodes to run job on
#SBATCH -p general # queue (partition) – general, emc
#SBATCH -t 01:30:00 # run time (hh:mm:ss) - 1.5 hours
#SBATCH --mail-user=otasdemir@vassar.edu
#SBATCH --mail-type=begin # email me when the job starts
#SBATCH --mail-type=end # email me when the job finishes
#commands to execute the job appear below the header

srun -n 1 python3 /home/otasdemir/work/centralStorage.py
