#!/bin/bash
#SBATCH -J orcunThesis # job name
#SBATCH -p general # queue (partition) – general, emc
#SBATCH --mail-user=otasdemir@vassar.edu
#SBATCH --mail-type=begin # email me when the job starts
#SBATCH --mail-type=end # email me when the job finishes
#SBATCH --nodes=1
#SBATCH --ntasks=25
#SBATCH --ntasks-per-node=25 # number of CPUs per node to run job on
#commands to execute the job appear below the header

srun -n 1 python3 /home/otasdemir/work/capture_ability_test.py


# 25 of them
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# srun -n 1 python3 /home/otasdemir/work/run.py &
# wait


